// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-zsjDB2TmTShQNJnfjqbR6HnCqVOcaQ8',
    appId: '1:838943067396:web:c77917f80aa0f958361451',
    messagingSenderId: '838943067396',
    projectId: 'messag-futter-curso',
    authDomain: 'messag-futter-curso.firebaseapp.com',
    storageBucket: 'messag-futter-curso.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwF29S62BjXTl_FWs1lB3hs-CfhNu1tv0',
    appId: '1:838943067396:android:e0720a7c727455da361451',
    messagingSenderId: '838943067396',
    projectId: 'messag-futter-curso',
    storageBucket: 'messag-futter-curso.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ed8WOyphE-IQqRvxyE9XEacAArHNMfg',
    appId: '1:838943067396:ios:0789725a60988bcc361451',
    messagingSenderId: '838943067396',
    projectId: 'messag-futter-curso',
    storageBucket: 'messag-futter-curso.appspot.com',
    iosClientId: '838943067396-45vqkh3tvb323u6f8of6vebtokslh1li.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5ed8WOyphE-IQqRvxyE9XEacAArHNMfg',
    appId: '1:838943067396:ios:0789725a60988bcc361451',
    messagingSenderId: '838943067396',
    projectId: 'messag-futter-curso',
    storageBucket: 'messag-futter-curso.appspot.com',
    iosClientId: '838943067396-45vqkh3tvb323u6f8of6vebtokslh1li.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifications',
  );
}
